import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { state } from "./state.js";
import { renderArchiveView } from "./ui-components.js";

const packageSource = readFileSync("package.json", "utf8");
const indexSource = readFileSync("index.html", "utf8");
const appSource = readFileSync("app.js", "utf8");
const eventSource = readFileSync("app-graph-events.js", "utf8");
const stateSource = readFileSync("state.js", "utf8");
const rendererSource = readFileSync("archive-graph-3d.js", "utf8");
const cssSource = readFileSync("components.css", "utf8");

assert.match(packageSource, /"three":/);
assert.match(packageSource, /archive-graph-3d\.js/);
assert.match(packageSource, /node_modules\/three\/build\/three\.module\.js/);
assert.match(packageSource, /OrbitControls\.js/);
assert.match(indexSource, /archive-graph-3d\.js/);
assert.match(indexSource, /type="importmap"/);
assert.match(indexSource, /"three": "\.\/node_modules\/three\/build\/three\.module\.js"/);
assert.match(appSource, /initArchiveGraph3D/);
assert.match(rendererSource, /THREE\.Scene/);
assert.match(rendererSource, /OrbitControls/);
assert.match(rendererSource, /data-archive-graph-3d/);
assert.match(rendererSource, /function buildGraphContext/);
assert.match(rendererSource, /connectedToActive/);
assert.match(rendererSource, /function shouldLabelNode/);
assert.match(rendererSource, /return node\.active;/);
assert.match(rendererSource, /let hoverLabel = null/);
assert.match(rendererSource, /const clearHoverLabel = \(\) =>/);
assert.match(rendererSource, /removeEventListener\("pointerleave", handlePointerLeave\)/);
assert.match(rendererSource, /!node\.active && !hoverLabel/);
assert.match(rendererSource, /function createHalo/);
assert.match(rendererSource, /function createStarCoreTexture/);
assert.match(rendererSource, /function createNodeStar/);
assert.match(rendererSource, /RELATION_DISTANCE_RINGS/);
assert.match(rendererSource, /SPATIAL_PRIORITY_LAYERS/);
assert.match(rendererSource, /function spatialPriorityScore/);
assert.match(rendererSource, /function priorityDepth/);
assert.match(rendererSource, /export function layoutArchiveGraphNodes/);
assert.match(rendererSource, /spatialPriority/);
assert.match(rendererSource, /materialQualityScore/);
assert.doesNotMatch(rendererSource, /NODE_DEPTH_SHELLS/);
assert.doesNotMatch(rendererSource, /depthParallax/);
assert.doesNotMatch(rendererSource, /depthSide/);
assert.match(rendererSource, /camera\.position\.set\(78, -46, 390\)/);
assert.match(rendererSource, /controls\.maxDistance = 1120/);
assert.match(rendererSource, /archive-graph-star-core/);
assert.match(rendererSource, /archive-graph-star-flare/);
assert.match(rendererSource, /archive-graph-star-corona/);
assert.match(rendererSource, /starGroups/);
assert.match(rendererSource, /degree \|\| 0/);
assert.match(rendererSource, /function formatTooltip/);
assert.match(rendererSource, /function summarizeBacklink/);
assert.match(rendererSource, /explicitLinkCount|backlinks/);
assert.match(rendererSource, /relationStrength/);
assert.match(rendererSource, /SPACE_BACKGROUND/);
assert.match(rendererSource, /space-dust/);
assert.match(rendererSource, /space-stars-far/);
assert.match(rendererSource, /space-stars-near/);
assert.match(rendererSource, /space-stars-core/);
assert.match(rendererSource, /NEBULA_CLOUDS/);
assert.match(rendererSource, /space-nebula-violet/);
assert.match(rendererSource, /function createNebulaTexture/);
assert.match(rendererSource, /function createNebulaCloud/);
assert.match(rendererSource, /SPACE_BACKDROP_FRAGMENT_SHADER/);
assert.match(rendererSource, /function createSpaceBackdropMaterial/);
assert.match(rendererSource, /function createSpaceBackdrop/);
assert.match(rendererSource, /function createPointStarTexture/);
assert.match(rendererSource, /function createMilkyWayParticleField/);
assert.match(rendererSource, /function createDistantGalaxySprites/);
assert.match(rendererSource, /space-photographic-backdrop/);
assert.match(rendererSource, /space-milky-way-particle-field/);
assert.match(rendererSource, /deep-space-galaxy-smudge/);
assert.match(rendererSource, /THREE\.ShaderMaterial/);
assert.match(rendererSource, /fbm\(vec3 p\)/);
assert.match(rendererSource, /smoothstep/);
assert.match(rendererSource, /photographicGrain/);
assert.match(rendererSource, /gl_FragCoord\.xy/);
assert.match(rendererSource, /LinearMipmapLinearFilter/);
assert.match(rendererSource, /THREE\.BackSide/);
assert.match(rendererSource, /THREE\.ACESFilmicToneMapping/);
assert.match(rendererSource, /THREE\.AdditiveBlending/);
assert.match(rendererSource, /constellation-line-glow/);
assert.match(rendererSource, /constellationLines/);
assert.match(rendererSource, /function relationIntensity/);
assert.match(rendererSource, /function relationLineOpacity/);
assert.match(rendererSource, /function relationGlowOpacity/);
assert.match(rendererSource, /function relationPulseAmount/);
assert.match(rendererSource, /function relationLineWidth/);
assert.match(rendererSource, /relationLane/);
assert.match(rendererSource, /space-photographic-grain/);
assert.match(rendererSource, /toneMappingExposure = 1\.08/);
assert.doesNotMatch(rendererSource, /toneMappingExposure = 1\.14/);
assert.match(rendererSource, /relationLineColor\(link\)/);
assert.match(rendererSource, /clock\.getElapsedTime/);
assert.match(cssSource, /\.archive-graph-3d-canvas/);
assert.match(cssSource, /\.archive-graph-3d::before/);
assert.match(cssSource, /inset 0 0 320px/);
assert.match(cssSource, /mix-blend-mode: screen/);
assert.match(cssSource, /rgba\(0, 0, 0, 0\.18\) 72%/);
assert.match(cssSource, /#060914/);
assert.match(cssSource, /\.archive-graph-context-actions button[\s\S]*background: var\(--panel-raised\);[\s\S]*color: var\(--text\);/);
assert.match(cssSource, /\.archive-graph-filter-rail/);
assert.match(cssSource, /\.archive-graph-filter-rail\.collapsed/);
assert.match(cssSource, /\.archive-graph-filter-group/);
assert.match(eventSource, /data-archive-graph-filter-reset/);
assert.match(eventSource, /data-archive-graph-filters-collapsed/);
assert.match(stateSource, /archiveGraphFiltersCollapsed/);

state.projects = [{ id: 10, name: "Levinas Study", note: "levinas totality infinity explanation" }];
state.tasks = [{ id: 20, projectId: 10, name: "Levinas task", note: "truth justice being" }];
state.archiveResources = [
  { id: 1, name: "Levinas totality infinity.pdf", type: "file", path: "G:\\levinas\\a.pdf", desc: "levinas truth justice explanation", tags: [], semanticEmbedding: [1, 0, 0] },
  { id: 2, name: "Levinas otherwise than being.pdf", type: "file", path: "G:\\levinas\\b.pdf", desc: "levinas subjectivity responsibility", tags: [], semanticEmbedding: [0.96, 0.04, 0] },
  { id: 3, name: "Levinas ethics notes.pdf", type: "file", path: "G:\\levinas\\c.pdf", desc: "levinas ethics responsibility", tags: [], semanticEmbedding: [0.93, 0.07, 0] },
  { id: 4, name: "Levinas archive link", type: "link", path: "https://example.com/levinas", desc: "levinas truth archive reference", tags: [], semanticEmbedding: [0.97, 0.03, 0] }
];
state.archiveResourceLinks = [{ resourceId: 1, targetType: "task", targetId: 20 }];
state.selectedArchiveResourceId = 1;
state.appSettings.archiveViewMode = "graph";
state.appSettings.archiveGraphDisplayMode = "graph3d";
state.appSettings.archiveGraphDepth = 2;
state.appSettings.archiveGraphKindFilter = "all";
state.appSettings.archiveGraphStrengthFilter = "all";
state.appSettings.archiveGraphFiltersCollapsed = false;

const graph3dHtml = renderArchiveView();
assert.match(graph3dHtml, /data-archive-graph-3d/);
assert.match(graph3dHtml, /data-archive-graph-3d-canvas/);
assert.match(graph3dHtml, /data-archive-graph-3d-payload/);
assert.match(graph3dHtml, /archive-graph-observatory/);
assert.match(graph3dHtml, /archive-graph-inspector-card/);
assert.match(graph3dHtml, /\uc120\ud0dd \uc790\ub8cc/);
assert.match(graph3dHtml, /\uc790\ub8cc \ud488\uc9c8/);
assert.match(graph3dHtml, /\uc774 \uc791\uc5c5\uc5d0\uc11c\uc758 \uc2e0\ub8b0\ub3c4/);
assert.match(graph3dHtml, /\uac00\uc7a5 \uac15\ud55c \uc5f0\uacb0/);
assert.match(graph3dHtml, /\uc2e0\ub8b0\ub3c4/);
assert.match(graph3dHtml, /\uba54\ubaa8/);
assert.match(graph3dHtml, /\uc5f0\uacb0\ub41c \uc791\uc5c5/);
assert.doesNotMatch(graph3dHtml, /\ud310\ub2e8 \uae30\uc900/);
assert.match(graph3dHtml, /data-archive-relation-strength="strong"/);
assert.match(graph3dHtml, /data-archive-relation-note="true"/);
assert.doesNotMatch(graph3dHtml, /Active Context/);
assert.doesNotMatch(graph3dHtml, />Archive Graph</);
assert.match(graph3dHtml, /archive-graph-filter-rail/);
assert.match(graph3dHtml, /archive-graph-filter-summary-button/);
assert.match(graph3dHtml, /data-archive-graph-filters-collapsed/);
assert.match(graph3dHtml, /aria-expanded="true"/);
assert.doesNotMatch(graph3dHtml, /data-archive-graph-filter-reset/);
assert.doesNotMatch(graph3dHtml, /\ud544\ud130 \uc811\uae30|\ud544\ud130 \uc5f4\uae30|\ucd08\uae30\ud654/);
assert.match(graph3dHtml, /data-archive-graph-kind-filter="all" class="active"/);
assert.match(graph3dHtml, /data-archive-graph-kind-filter="files"/);
assert.match(graph3dHtml, /data-archive-graph-kind-filter="links"/);
assert.match(graph3dHtml, /data-archive-graph-strength-filter="strong"/);
assert.match(graph3dHtml, /data-archive-graph-strength-filter="review"/);
const graph3dPayloadText = graph3dHtml.match(/<script type="application\/json" data-archive-graph-3d-payload>([\s\S]*?)<\/script>/)?.[1] || "";
const graph3dPayload = JSON.parse(graph3dPayloadText);
assert.ok(graph3dPayload.nodes.length >= 3);
assert.ok(graph3dPayload.links.length >= 1);
assert.equal(graph3dPayload.meta.graphKindFilter, "all");
assert.equal(graph3dPayload.meta.graphStrengthFilter, "all");
assert.ok(graph3dPayload.meta.graphFileCount >= 3);
assert.ok(graph3dPayload.meta.graphLinkCount >= 1);
assert.equal(graph3dPayload.nodes.find((node) => node.id === "resource:1").explicitLinkCount, 1);
assert.match(JSON.stringify(graph3dPayload.nodes.find((node) => node.id === "resource:1").backlinks), /Levinas task/);
assert.match(JSON.stringify(graph3dPayload.nodes.find((node) => node.id === "resource:1").backlinks), /relationType/);
assert.ok(graph3dPayload.nodes.every((node) => String(node.id).startsWith("resource:")));
assert.ok(graph3dPayload.links.every((link) => String(link.source).startsWith("resource:") && String(link.target).startsWith("resource:")));
assert.match(graph3dHtml, /data-archive-graph-display-mode="graph3d"[^>]*>3D Graph/);
assert.match(graph3dHtml, /data-archive-graph-depth="2" class="active"/);
assert.match(graph3dHtml, /archive-graph-depth-note/);
assert.match(graph3dHtml, /\uc120\ud0dd \uc790\ub8cc\uc5d0\uc11c \uc5b4\ub514\uae4c\uc9c0 \ud3bc\uce60\uc9c0/);
assert.match(graph3dHtml, /\uc9c1\uc811 \uc5f0\uacb0\uc5d0\uc11c \ud55c \ubc88 \ub354 \ud655\uc7a5/);
assert.match(graph3dHtml, /\ubc94\uc704/);
assert.match(graph3dHtml, /\uc9c1\uc811 \uc5f0\uacb0/);
assert.match(graph3dHtml, /\ud55c \ubc88 \ub354/);
assert.match(graph3dHtml, /\ub113\uac8c \ubcf4\uae30/);
assert.doesNotMatch(graph3dHtml, /\uac70\ub9ac/);
assert.doesNotMatch(graph3dHtml, /\+1\ub2e8\uacc4/);
assert.doesNotMatch(graph3dHtml, /archive-graph-depth-legend/);
assert.doesNotMatch(graph3dHtml, /archive-graph-depth-dot/);
assert.doesNotMatch(graph3dHtml, /<b>0<\/b>/);
assert.doesNotMatch(graph3dHtml, /<b>1<\/b>/);
assert.doesNotMatch(graph3dHtml, /<b>2<\/b>/);
assert.match(graph3dHtml, /\uc120\ud0dd \uc790\ub8cc/);
assert.match(graph3dHtml, /\uc9c1\uc811 \uc5f0\uacb0/);
assert.match(graph3dHtml, /\ud55c \ubc88 \ub354 \ud655\uc7a5/);
assert.match(graph3dHtml, /\uc120\ud0dd \uc790\ub8cc \u00b7 \uc9c1\uc811 \uc5f0\uacb0 \u00b7 \ud55c \ubc88 \ub354 \ud655\uc7a5/);
assert.doesNotMatch(graph3dHtml, /data-archive-graph-pan-catcher/);

state.appSettings.archiveGraphFiltersCollapsed = true;
const collapsedFilterHtml = renderArchiveView();
assert.match(collapsedFilterHtml, /archive-graph-filter-rail collapsed/);
assert.match(collapsedFilterHtml, /aria-expanded="false"/);
assert.match(collapsedFilterHtml, /archive-graph-filter-summary/);

state.appSettings.archiveGraphKindFilter = "links";
const linkFilteredHtml = renderArchiveView();
const linkFilteredPayloadText = linkFilteredHtml.match(/<script type="application\/json" data-archive-graph-3d-payload>([\s\S]*?)<\/script>/)?.[1] || "";
const linkFilteredPayload = JSON.parse(linkFilteredPayloadText);
assert.equal(linkFilteredPayload.meta.graphKindFilter, "links");
assert.ok(linkFilteredPayload.meta.hiddenByGraphFilters >= 1);
assert.ok(linkFilteredPayload.nodes.some((node) => node.id === "resource:4" && node.kind === "link"));
assert.ok(linkFilteredPayload.nodes.every((node) => node.active || node.kind === "link"));
assert.match(linkFilteredHtml, /data-archive-graph-kind-filter="links" class="active"/);
assert.match(linkFilteredHtml, /archive-graph-filter-reset-button/);
assert.match(linkFilteredHtml, /data-archive-graph-filter-reset/);
assert.match(linkFilteredHtml, /aria-label="Space \ud544\ud130 \ucd08\uae30\ud654"/);

state.appSettings.archiveGraphKindFilter = "all";
state.appSettings.archiveGraphDisplayMode = "graph2d";
const graph2dHtml = renderArchiveView();
assert.match(graph2dHtml, /data-archive-graph-pan-catcher/);
const graph2dPayloadText = graph2dHtml.match(/<script type="application\/json" data-archive-graph-payload>([\s\S]*?)<\/script>/)?.[1] || "";
const graph2dPayload = JSON.parse(graph2dPayloadText);
assert.ok(graph2dPayload.nodes.length >= 3);
assert.ok(graph2dPayload.nodes.some((node) => String(node.id).startsWith("resource:")));
assert.ok(graph2dPayload.nodes.some((node) => String(node.id).startsWith("task:") || String(node.id).startsWith("project:")));
assert.ok(graph2dPayload.links.every((link) => String(link.source).startsWith("resource:") || String(link.target).startsWith("resource:")));
assert.ok(graph2dPayload.links.some((link) => link.relationEdgeKey && link.resourceId && link.targetType && link.targetId));
assert.doesNotMatch(graph2dHtml, /data-archive-graph-3d-canvas/);

console.log("archive 3d graph markup ok");
